config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  devise_for :users
  
  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :likes
  end

  resources :users
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post
	belongs_to :user

	validates :text, presence: true
	validates :text, length: { maximum: 200,
    too_long: "Your comment must contain at most %{count} characters" }

  def username
  	user.username
  end

end

app/models/like.rb
class Like < ActiveRecord::Base

	belongs_to :user
	belongs_to :post
	
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :likes
	has_many :comments
	belongs_to :user

	has_attached_file :image, :storage => :s3,
                      :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
                      :styles => { :medium => "500x500#", :thumb => "150x150#" }, :default_url => "/images/:style/missing.png"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates_attachment_presence :image

	def s3_credentials
		{:bucket => 'photo-bucket-elewis', :access_key_id => Rails.application.secrets.access_key_id, :secret_access_key => Rails.application.secrets.secret_access_key}
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :uniqueness => {
    :case_sensitive => false }, presence: true, length: { minimum: 3, maximum: 18,
    too_long: "Your username must contain between 3 and 18 characters" }


  attr_accessor :login

  has_many :likes
  has_many :posts
  has_many :comments

  def self.find_for_database_authentication(warden_conditions)
   	conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:show, :index]  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	include ActionView::Helpers::DateHelper
	include ActionView::Helpers::UrlHelper

	def create
		if user_signed_in?
			@post = Post.find(params[:post_id])
			@comment = @post.comments.create(params[:comment].permit(:text))
			@comment.user_id = current_user.id
			if @comment.save
				render json: { commentText: @comment.text, 
							   			 commentUser: link_to(@comment.username, user_path(@comment.user)),
							   			 commentTimestamp: time_ago_in_words(@comment.created_at) }
			end
		else
			redirect_to '/users/sign_in'
		end
	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	include LikesHelper
	include ActionView::Helpers::TextHelper

	def create
		@post = Post.find(params[:post_id])
		@like = @post.likes.find_by(:user_id => current_user.id)
		if @like.nil?
			@post.likes.create(:user_id => current_user.id).save!
			render_likes('Unlike')
		else
			@like.destroy
			render_likes('Like')
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(params[:post].permit(:caption, :image))
		@post.user_id = current_user.id
		@post.save!
		redirect_to posts_path
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		@user = User.find(@post.user_id)
		respond_to do |format|
        	format.html { redirect_to root_path }
        	format.js { render :template => 'posts/show.js.erb' }
      	end
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.user_id == current_user.id
			@post.destroy
			redirect_to posts_path
			flash[:notice] = "Your post was successfully destroyed"
		else
			redirect_to posts_path
		end
	end

	def edit
		@post = Post.find(params[:id])
		if current_user.id == @post.user_id
			render 'edit'
		else
			redirect_to posts_path
		end
	end

	def update
		@post = Post.find(params[:id])
		@post.update(params[:post].permit(:caption))
		redirect_to posts_path
		flash[:notice] = "Your post was successfully updated"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
		@user_title = @user.username
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
	def render_likes(string)
		render json: { updatedlikesCount: pluralize(@post.likes.count, 'like'), 
					   postId: params[:post_id], 
					   link: string }
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<% if current_user %>
	<section id='signedin-modal'>
		<%= bootstrap_form_for([@post, @comment], remote: true) do |f| %>
		<%= f.text_area :text, :placeholder => "Leave a comment", hide_label: true %>
		<%= f.submit 'Submit comment' %>
		<% end %>
	</section>
<% else %>
		<%= bootstrap_form_for([@post, @comment]) do |f| %>
		<%= f.text_area :text, :placeholder => "Leave a comment", hide_label: true %>
		<%= f.submit 'Submit comment' %>
		<% end %>
<% end %>

app/views/comments/_show.html.erb
<ul class="list-group">
   	<% @post.comments.each do |comment| %>
		<li class="list-group-item">
			<p class="list-group-item-text">
		        <%= link_to comment.username, user_path(comment.user) %>
		    </p>
		    <p class="list-group-item-heading">
		        <%= comment.text %>
		    </p>
		    <i class='timestamp'>
		      	<%= time_ago_in_words(comment.created_at) %> ago
		    </i>
		</li>
	<% end %>
</ul>

app/views/layouts/_modal.html.erb
<div id="ajax-modal" class="modal hide fade" tabindex="-1">
  <div class='modal-body'>
    <div class="modal-body-content"></div>
    <div class="ajax-loader"></div>
  </div>
</div>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all' %>

app/views/layouts/_posts.erb
<div id="container" class='masonry'>
	<% if @posts %>
		<% @posts.each do |post| %>
			<div class='item'>
				<%= link_to image_tag(post.image.url(:medium)), post_path(post), class: 'image-link', remote: true, data: { toggle: "modal", target: "#ajax-modal" } %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<html>
<head>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag 'application' %>
  	<title>funstagram</title>
</head>
<body>
	<header class='header'>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<h1 id='header-title'><a href='/posts'>Funstagram</a></h1>
		<h2 id='user-title'><%= @user_title %></h2>
	</header>
	<div id='main-container' class='container-fluid'>
		<div id='sessions-links'>
			<% if user_signed_in? %>
				<%= link_to 'Sign out', destroy_user_session_path, method: :delete %> 
				<div id='add-post'>
					<%= link_to 'Add a post', new_post_path, class: 'create-post' %>
				</div>
				<div id='signedin-as'>
					<p>Signed in as <%= link_to "#{current_user.username}", user_path(current_user) %></p>
				</div>
			<% else %>
				<% if @posts %>
					<%= link_to 'Sign in', new_user_session_path %> 
					<%= link_to 'Sign up', new_user_registration_path %> 
				<% end %>
			<% end %>
		</div>	
		<div id="main-content" class='container'>
			<%= render 'layouts/posts' %>
		</div>
		<%= yield %>
	</div>
	<%= render 'layouts/modal' %>
</body>
</html>

app/views/likes/_new.html.erb
<% if current_user %>
	<% if @post.likes.find_by(:user_id => current_user.id).nil? %>
		<%= link_to 'Like', post_likes_path(@post), id: 'like-link', method: :post, :remote => true, class: 'btn btn-default' %>
	<% else %>
		<%= link_to 'Unlike', post_likes_path(@post), id: 'like-link', method: :post, :remote => true, class: 'btn btn-default' %>
	<% end %>
<% else %>
	<%= link_to 'Like', post_likes_path(@post), method: :post, class: 'btn btn-default' %>
<% end %>

app/views/posts/_show.html.erb
<section id='modal-main'>
	<div id='img-wrapper'>
		<%= image_tag @post.image.url(:medium) %>
	</div>
	<section id='user-options'>
		<% if current_user %>
			<% if current_user.id == @post.user_id %>
				<%= link_to 'Delete', post_path(@post), method: :delete, :confirm => "Are you sure you would like to delete this post?" %>
				<%= link_to 'Edit', edit_post_path(@post) %>
			<% end %>
		<% end %>
	</section>
</section>
<section id='modal-comments'>
	<section id='img-info'>
		<div id='username'>
			<%= link_to "#{@user.username}", user_path(@user) %>
		</div>
		<div id='caption'>
			<%= @post.caption %>
		</div>
		<i class='timestamp'><%= time_ago_in_words(@post.created_at) %> ago</i>
		<section id='like-links'>
			<span><%= pluralize(@post.likes.count, 'like') %></span>
		</section>
	</section>
	<section id='comments-list'>
		<%= render 'comments/show' %>
	</section>
	<section class='modal-form'>
		<%= render 'comments/new' %>
		<div id="link-name">
			<%= render 'likes/new' %>
		</div>
	</section>
</section>

app/views/posts/edit.html.erb
<%= bootstrap_form_for @post, method: :put do |f| %>
	<%= f.label :caption %>
	<%= f.text_area :caption %>
	<%= f.button 'Submit' %>
<% end %>

app/views/posts/new.html.erb
<section class='bootstrap-form'>
	<%= bootstrap_form_for @post, :html => { :multipart => true } do |f| %>
		<%= f.text_area :caption %>
		<span><%= f.file_field :image, class: "btn btn-file" %></span>
		<%= f.submit 'Submit' %>
	<% end %>
</section>

app/views/posts/show.html.erb
<section id='modal-main'>
	<%= image_tag @post.image.url(:medium) %><br>
	<strong><%= @post.caption %></strong>
	<section class='like-links'>
		<span><%= pluralize(@post.likes.count, 'like') %></span>
		<% if current_user %>
			<a class="like-link" data-method="post" data-remote="true" href="/posts/1/likes" rel="nofollow"><span class="link-name">Like</span></a>
		<% end %>
	</section>
	<section id='user-options'>
		<% if current_user.id == @post.user_id %>
			<%= link_to 'Delete', post_path(@post), method: :delete, :confirm => "Are you sure you would like to delete this post?" %>
			<%= link_to 'Edit', edit_post_path(@post) %>
		<% end %>
	</section>
</section>
<section id='modal-comments'>
	<section id='comments-list'>
		<ul>
			<% @post.comments.each do |comment| %>
			<li>
				<div id='comment-text'>
					<%= comment.text %>
				</div>
				<div id='comment-user'>
					<%= comment.username %>
				</div>
			</li>
			<% end %>
		</ul>
	</section>
<%= render 'comments/new' %>
</section>

<%= csrf_meta_tags %>

app/views/posts/show.js.erb
var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#ajax-modal';

$(title).html('');
$(modal).css('visibility', 'visible');
$(loader).fadeToggle('fast', function() {
  $(loader).fadeOut('slow');
  $(content).html('<%= j render("show") %>');
  $(modal).modal();
});

$(modal).on('hidden.bs.modal', function() {
  $(this).css('visibility', 'hidden');
});